version: 2

sources:
  - name: erp
    description: 'Adventure Works ERP system source (SAP).'
    database: fea24_6
    schema: raw_adventure_works
    tables:
      - name: address
        description: 'Street address information for customers, employees, and vendors.'
        columns:
          - name: addressid
            description: 'Primary key for Address records.'
          - name: stateprovinceid
            description: 'Foreign Key to unique identification number for the state or province.'
          - name: addressline1
            description: 'First street address line.'
          - name: addressline2
            description: 'Second street address line.'
          - name: city
            description: 'Name of the city.'
          - name: postalcode
            description: 'Postal code for the street address.'
          - name: spatiallocation
            description: 'Latitude and longitude of this address.'
          - name: rowguid
            description: 'number uniquely identifying the record.'
          - name: modifieddate
            description: 'Date and time the record was last updated.'

      - name: countryregion
        description: 'Table containing the ISO standard codes for countries and regions.'
        columns:
          - name: CountryRegionCode
            description: Primary key for Country Region records.'
          - name: Name
            description: 'Country or region name.'
          - name: modifieddate
            description: 'Date and time the record was last updated.'
      
      - name: customer
        description: 'Table with customer information.'
        columns:
          - name: customerid
            description: 'Primary key for Customer records.'
          - name: personid
            description: 'Foreign key for Person records.'
          - name: storeid
            description: 'Foreign key for Store records.'
          - name: territoryid
            description: 'Foreign key to the territory in which the customer is located.'
          - name: accountnumber
            description: 'Unique number identifying the customer assigned by the accounting system.'
          - name: rowguid
            description: 'number uniquely identifying the record.'
          - name: modifieddate
            description: 'Date and time the record was last updated.'

      - name: person
        description: >
          Table of persons involved with AdventureWorks:
          employees, customer contacts, and vendor contacts.
        columns:
          - name: businessentityid
            description: 'Primary key for Person records.'
          - name: persontype
            description: >
              Primary type of person. Indicates whether the person is:
              Store contact (SC), Individual [retail] customer (IN), Sales person (SP),
              Employee [non-sales] (EM), Vendor contact (VC) or General contact (GC).
          - name: namestyle
            description: >
              Flag to indicate if the data in firstname and lastname are stored 
              in western style order (0) [firstname, last name] or the opposite (1).
          - name: title
            description: 'A courtesy title attributed to the person.'
          - name: firstname
            description: 'First name of the person.'
          - name: middlename
            description: 'Middle name of the person.'
          - name: lastname
            description: 'Last name of the person.'
          - name: suffix
            description: 'Surname suffix.'
          - name: emailpromotion
            description: |
              Flag that indicates if: 
              0 = Contact does not wish to receive e-mail promotions,
              1 = Contact does wish to receive e-mail promotions from AdventureWorks,
              2 = Contact does wish to receive e-mail promotions from AdventureWorks and selected partners.
          - name: additionalcontactinfo 
            description: 'Additional contact information about the person stored in xml format.'
          - name: demographics
            description: 'Personal information such as hobbies, and income collected from online shoppers.'
          - name: rowguid
            description: 'number uniquely identifying the record.'
          - name: modifieddate
            description: 'Date and time the record was last updated.'
    
      - name: product
        description: 'Table of products sold or used in the manfacturing of sold products.'
        columns:
          - name: productid
            description: 'Primary key for Product records.'
          - name: name
            description: 'Name of the product.'        
          - name: productnumber
            description: 'Unique product identification number.'
          - name: makeflag 
            description: 'Flag to indicate if the product is purchased (0) or manufactured in-house (1).'
          - name: finishedgoodsflag
            description: 'Flag to indicate if the product is salable (1) or not (0).'
          - name: color
            description: 'Product color.'
          - name: safetystocklevel
            description: 'Minimum inventory quantity.'
          - name: reorderpoint
            description: 'Inventory level that triggers a purchase order or work order.'
          - name: standardcost
            description: 'Standard cost of the product.'
          - name: listprice
            description: 'Selling price.'
          - name: Size
            description: 'Product size.'
          - name: sizeunitmeasurecode
            description: 'Unit of measure for Size column.'
          - name: weightunitmeasurecode
            description: 'Unit of measure for Weight column.'
          - name: weight
            description: 'Product weight.'
          - name: daystomanufacture
            description: 'Number of days required to manufacture the product.'
          - name: productline 
            description: 'Indicates whether the product line is Road (R), Mountain (M), Touring (T), or Standard (S).'
          - name: class
            description: 'Indicates whether the product class is High (H), Medium (M), or Low  (L).'
          - name: style
            description: 'Indicates whether the product style is Womens (W), Mens (M), or Universal (U).'
          - name: productsubcategoryid
            description: 'Foreign key to product subcategory.'
          - name: productmodelid
            description: 'Foreign Key to the product model.'
          - name: sellstartdate
            description: 'Date the product was available for sale.'
          - name: sellenddate
            description: 'Date the product was no longer available for sale.'
          - name: discontinueddate
            description: 'Date the product was discontinued.'
          - name: rowguid
            description: 'number uniquely identifying the record.'
          - name: modifieddate
            description: 'Date and time the record was last updated.'

      - name: productcategory
        description: 'Table with records of product categories.'
        columns:
          - name: productcategoryid
            description: 'Primary key for Product Category records.'
          - name: name
            description: 'Name of the product category.'
          - name: rowguid
            description: 'number uniquely identifying the record.'
          - name: modifieddate
            description: 'Date and time the record was last updated.'
      
      - name: productsubcategory
        description: 'Table with records of product subcategories.'
        columns:
          - name: productsubcategoryid
            description: 'Primary key for Product Subcategory records.'
          - name: productcategoryid
            description: 'Foreign key for Product Category records.'
          - name: name
            description: 'Name of the product subcategory.'
          - name: rowguid
            description: 'number uniquely identifying the record.'
          - name: modifieddate
            description: 'Date and time the record was last updated.'

      - name: store
        description: 'Table with stores information.'
        columns:
          - name: businessentityid
            description: 'Primary key for Store records.'
          - name: salespersonid
            description: 'Foreign key to the sales person assigned to the customer.'
          - name: name
            description: 'Name of the store.'
          - name: demographics
            description: 'Demographic informationg about the store.'
          - name: rowguid
            description: 'number uniquely identifying the record.'
          - name: modifieddate
            description: 'Date and time the record was last updated.'
